# Generated by Django 5.2.9 on 2025-12-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('salons', '0002_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylistprofile',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stylists', to='salons.salon', verbose_name='سالن'),
        ),
    ]
