# Generated by Django 5.2.9 on 2025-12-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonmanagerprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID برای ارسال اعلان\u200cهای تلگرام', max_length=50, null=True, unique=True, verbose_name='شناسه چت تلگرام'),
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID برای ارسال اعلان\u200cهای تلگرام', max_length=50, null=True, unique=True, verbose_name='شناسه چت تلگرام'),
        ),
    ]
