# Generated by Django 5.2.9 on 2025-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_salonmanagerprofile_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='telegram_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام در تلگرام'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram User ID برای عملیات API', null=True, verbose_name='شناسه کاربر تلگرام'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (بدون @)', max_length=100, null=True, verbose_name='نام کاربری تلگرام'),
        ),
        migrations.AddField(
            model_name='salonmanagerprofile',
            name='telegram_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام در تلگرام'),
        ),
        migrations.AddField(
            model_name='salonmanagerprofile',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram User ID برای عملیات API', null=True, verbose_name='شناسه کاربر تلگرام'),
        ),
        migrations.AddField(
            model_name='salonmanagerprofile',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (بدون @)', max_length=100, null=True, verbose_name='نام کاربری تلگرام'),
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='telegram_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام در تلگرام'),
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram User ID برای عملیات API', null=True, verbose_name='شناسه کاربر تلگرام'),
        ),
        migrations.AddField(
            model_name='stylistprofile',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (بدون @)', max_length=100, null=True, verbose_name='نام کاربری تلگرام'),
        ),
    ]
