# Generated by Django 5.2.9 on 2025-12-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_telegram_user_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='telegram_user_id',
            field=models.CharField(blank=True, help_text='User ID ثابت کاربر در تلگرام', max_length=50, null=True, verbose_name='شناسه کاربر تلگرام'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری تلگرام'),
        ),
        migrations.AlterField(
            model_name='salonmanagerprofile',
            name='telegram_user_id',
            field=models.CharField(blank=True, help_text='User ID ثابت کاربر در تلگرام', max_length=50, null=True, verbose_name='شناسه کاربر تلگرام'),
        ),
        migrations.AlterField(
            model_name='salonmanagerprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری تلگرام'),
        ),
        migrations.AlterField(
            model_name='stylistprofile',
            name='telegram_user_id',
            field=models.CharField(blank=True, help_text='User ID ثابت کاربر در تلگرام', max_length=50, null=True, verbose_name='شناسه کاربر تلگرام'),
        ),
        migrations.AlterField(
            model_name='stylistprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری تلگرام'),
        ),
    ]
