# Generated by Django 5.2.9 on 2025-12-14 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام سالن')),
                ('photo', models.ImageField(upload_to='salon_photos/', verbose_name='عکس سالن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('gender_type', models.CharField(choices=[('male', 'مردانه'), ('female', 'زنانه')], help_text='مردانه فقط برای مردان، زنانه فقط برای زنان', max_length=10, verbose_name='نوع سالن')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='میانگین امتیاز')),
                ('total_ratings', models.IntegerField(default=0, verbose_name='تعداد امتیازها')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='accounts.salonmanagerprofile', verbose_name='مدیر سالن')),
            ],
            options={
                'verbose_name': 'سالن',
                'verbose_name_plural': 'سالن\u200cها',
                'ordering': ['-average_rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('service_type', models.CharField(choices=[('eyelashes', 'خدمات مژه'), ('lips', 'خدمات لب'), ('beard_trim', 'اصلاح ریش'), ('makeup', 'آرایش'), ('hair_color', 'رنگ مو'), ('haircut', 'کوتاهی مو'), ('facial_hair', 'اصلاح ابرو و صورت'), ('nails', 'خدمات ناخن'), ('piercing', 'سوراخ کردن'), ('facial', 'مراقبت از پوست'), ('shave', 'اصلاح')], max_length=50, verbose_name='نوع خدمت')),
                ('custom_name', models.CharField(blank=True, help_text='نام خاص برای این خدمت (اختیاری)', max_length=100, verbose_name='نام سفارشی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='مدت زمان (دقیقه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon', verbose_name='سالن')),
                ('stylist', models.ForeignKey(blank=True, help_text='اگر خالی باشد، همه آرایشگرها این سرویس را ارائه می\u200cدهند', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.stylistprofile', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['salon', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salons.salon', verbose_name='سالن')),
                ('stylist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='accounts.stylistprofile', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='salon',
            index=models.Index(fields=['gender_type', 'average_rating'], name='salons_salo_gender__b3b273_idx'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.CheckConstraint(condition=models.Q(('salon__isnull', False), ('stylist__isnull', False), _connector='OR'), name='workinghours_has_salon_or_stylist'),
        ),
    ]
