# Generated by Django 5.2.9 on 2025-12-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('makeup', 'آرایش'), ('facial_hair', 'اصلاح ابرو و صورت'), ('eyelashes', 'خدمات مژه'), ('piercing', 'سوراخ کردن'), ('lips', 'خدمات لب'), ('beard_trim', 'اصلاح ریش'), ('haircut', 'کوتاهی مو'), ('facial', 'مراقبت از پوست'), ('hair_color', 'رنگ مو'), ('shave', 'اصلاح'), ('nails', 'خدمات ناخن')], max_length=50, verbose_name='نوع خدمت'),
        ),
    ]
