# Generated by Django 5.2.9 on 2025-12-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('hair_color', 'رنگ مو'), ('haircut', 'کوتاهی مو'), ('nails', 'خدمات ناخن'), ('eyelashes', 'خدمات مژه'), ('facial_hair', 'اصلاح ابرو و صورت'), ('shave', 'اصلاح'), ('piercing', 'سوراخ کردن'), ('facial', 'مراقبت از پوست'), ('lips', 'خدمات لب'), ('beard_trim', 'اصلاح ریش'), ('makeup', 'آرایش')], max_length=50, verbose_name='نوع خدمت'),
        ),
    ]
