# Generated by Django 5.2.9 on 2025-12-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('nails', 'خدمات ناخن'), ('haircut', 'کوتاهی مو'), ('makeup', 'آرایش'), ('eyelashes', 'خدمات مژه'), ('facial_hair', 'اصلاح ابرو و صورت'), ('piercing', 'سوراخ کردن'), ('lips', 'خدمات لب'), ('shave', 'اصلاح'), ('beard_trim', 'اصلاح ریش'), ('hair_color', 'رنگ مو'), ('facial', 'مراقبت از پوست')], max_length=50, verbose_name='نوع خدمت'),
        ),
    ]
