# Generated by Django 5.2.9 on 2025-12-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('piercing', 'سوراخ کردن'), ('hair_color', 'رنگ مو'), ('makeup', 'آرایش'), ('nails', 'خدمات ناخن'), ('beard_trim', 'اصلاح ریش'), ('eyelashes', 'خدمات مژه'), ('shave', 'اصلاح'), ('facial', 'مراقبت از پوست'), ('lips', 'خدمات لب'), ('haircut', 'کوتاهی مو'), ('facial_hair', 'اصلاح ابرو و صورت')], max_length=50, verbose_name='نوع خدمت'),
        ),
    ]
