# Generated by Django 5.2.9 on 2025-12-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('haircut', 'کوتاهی مو'), ('shave', 'اصلاح'), ('hair_color', 'رنگ مو'), ('beard_trim', 'اصلاح ریش'), ('nails', 'خدمات ناخن'), ('lips', 'خدمات لب'), ('facial_hair', 'اصلاح ابرو و صورت'), ('makeup', 'آرایش'), ('eyelashes', 'خدمات مژه'), ('piercing', 'سوراخ کردن'), ('facial', 'مراقبت از پوست')], max_length=50, verbose_name='نوع خدمت'),
        ),
    ]
