# Generated by Django 5.2.9 on 2025-12-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('facial', 'مراقبت از پوست'), ('nails', 'خدمات ناخن'), ('piercing', 'سوراخ کردن'), ('hair_color', 'رنگ مو'), ('haircut', 'کوتاهی مو'), ('lips', 'خدمات لب'), ('beard_trim', 'اصلاح ریش'), ('facial_hair', 'اصلاح ابرو و صورت'), ('eyelashes', 'خدمات مژه'), ('makeup', 'آرایش'), ('shave', 'اصلاح')], max_length=50, verbose_name='نوع خدمت'),
        ),
    ]
