# Generated by Django 5.2.9 on 2025-12-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('haircut', 'کوتاهی مو'), ('beard_trim', 'اصلاح ریش'), ('eyelashes', 'خدمات مژه'), ('facial', 'مراقبت از پوست'), ('piercing', 'سوراخ کردن'), ('shave', 'اصلاح'), ('lips', 'خدمات لب'), ('nails', 'خدمات ناخن'), ('facial_hair', 'اصلاح ابرو و صورت'), ('hair_color', 'رنگ مو'), ('makeup', 'آرایش')], max_length=50, verbose_name='نوع خدمت'),
        ),
    ]
