# Generated by Django 5.2.9 on 2025-12-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='auto_approve_appointments',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، نوبت\u200cها بلافاصله تأیید می\u200cشوند', verbose_name='تأیید خودکار نوبت\u200cها'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('facial', 'مراقبت از پوست'), ('facial_hair', 'اصلاح ابرو و صورت'), ('nails', 'خدمات ناخن'), ('lips', 'خدمات لب'), ('hair_color', 'رنگ مو'), ('makeup', 'آرایش'), ('shave', 'اصلاح'), ('beard_trim', 'اصلاح ریش'), ('haircut', 'کوتاهی مو'), ('eyelashes', 'خدمات مژه'), ('piercing', 'سوراخ کردن')], max_length=50, verbose_name='نوع خدمت'),
        ),
    ]
