# Generated by Django 5.2.9 on 2025-12-14 12:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_stylistprofile_salon'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز (1-5)')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='appointments.appointment', verbose_name='نوبت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.customerprofile', verbose_name='مشتری')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.stylistprofile', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیازات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stylist', 'rating'], name='ratings_rat_stylist_dc8bab_idx'), models.Index(fields=['created_at'], name='ratings_rat_created_3445a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'appointment'), name='unique_rating_per_appointment')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تأیید شده')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment', verbose_name='نوبت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.customerprofile', verbose_name='مشتری')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.stylistprofile', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stylist', 'is_approved', '-created_at'], name='ratings_rev_stylist_7effc2_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'appointment'), name='unique_review_per_appointment')],
            },
        ),
    ]
