# Generated by Django 5.2.9 on 2025-12-14 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_stylistprofile_salon'),
        ('salons', '0002_alter_service_service_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('appointment_date', models.DateField(verbose_name='تاریخ نوبت')),
                ('appointment_time', models.TimeField(verbose_name='ساعت نوبت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('customer_notes', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL, verbose_name='لغو شده توسط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.customerprofile', verbose_name='مشتری')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='salons.service', verbose_name='خدمت')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.stylistprofile', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['stylist', 'appointment_date', 'status'], name='appointment_stylist_7c3efa_idx'), models.Index(fields=['customer', 'appointment_date'], name='appointment_custome_49e85e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('stylist', 'appointment_date', 'appointment_time'), name='unique_active_appointment_per_stylist_datetime')],
            },
        ),
    ]
