# Generated by Django 5.2.9 on 2025-12-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_webhook_integration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='appointment_status_b3d279_idx',
            old_name='appointment_status_4b3e5c_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='appointment_appoint_837c67_idx',
            old_name='appointment_appoint_8a7f2d_idx',
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
    ]
