# Generated by Django 5.2.9 on 2025-12-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_appointment_status_4b3e5c_idx_appointment_status_b3d279_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='webhook_confirmed_sent',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='webhook_created_sent',
        ),
        migrations.DeleteModel(
            name='WebhookDelivery',
        ),
    ]
