# Generated by Django 5.2.9 on 2025-12-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_webhook_confirmed_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='دلیل لغو'),
        ),
    ]
