# Generated by Django 5.2.9 on 2025-12-22 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When chat was locked', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='locked_by_admin',
            field=models.ForeignKey(blank=True, help_text='Admin who has locked/claimed this chat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
